[tools]
usage = "latest"
fd    = "latest"
fzf   = "latest"
jq    = "latest"
gron  = "latest"
rg    = "latest"
lua   = "latest"
node  = "latest"

# Install cargo via rustup:
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
"cargo:bacon" = { version = "latest", locked = true, features = "clipboard sound" }
"cargo:stylua" = "latest"
# requires clang install: `sudo apt install clang`
"cargo:tree-sitter-cli" = { version = "latest", locked = true }

